// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKoAlLrO79ZQi9iRiqUbS5DNM7s9srOO4',
    appId: '1:261621588901:web:08cc11e759fb3db3753e4c',
    messagingSenderId: '261621588901',
    projectId: 'aistcargo',
    authDomain: 'aistcargo.firebaseapp.com',
    storageBucket: 'aistcargo.appspot.com',
    measurementId: 'G-HF8VS70CXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbTJMePNFbEM9-r-d4skCGLYncqb1YIw',
    appId: '1:261621588901:android:977cea83438ee2ef753e4c',
    messagingSenderId: '261621588901',
    projectId: 'aistcargo',
    storageBucket: 'aistcargo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfHGokZe3jPQ3FkFdBpvTUqIa9e10lI88',
    appId: '1:261621588901:ios:4271e9b015f6503f753e4c',
    messagingSenderId: '261621588901',
    projectId: 'aistcargo',
    storageBucket: 'aistcargo.appspot.com',
    iosClientId: '261621588901-fihju7dkbtdfb68futdak7brvosmfieh.apps.googleusercontent.com',
    iosBundleId: 'kg.besoft.aistcargo',
  );
}
